package Vistas.MenuPrincipal;
import javax.swing.JDesktopPane;

public class FrmPrincipal extends  javax.swing.JFrame {
    public GestorVistaPrincipal gestorVista;
 
    
    public FrmPrincipal() {
        initComponents();
    }

    public FrmPrincipal(GestorVistaPrincipal aThis) {
        initComponents();
        gestorVista=aThis;
    }


    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jmenu = new javax.swing.JMenuBar();
        mnConfiguracion = new javax.swing.JMenu();
        mnuProyecto = new javax.swing.JMenuItem();
        mnuTipoProyecto = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo");

        escritorio.setBackground(new java.awt.Color(255, 51, 51));

        jmenu.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N

        mnConfiguracion.setText("Configuración");
        mnConfiguracion.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N

        mnuProyecto.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        mnuProyecto.setText("Proyecto");
        mnuProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProyectoActionPerformed(evt);
            }
        });
        mnConfiguracion.add(mnuProyecto);

        mnuTipoProyecto.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        mnuTipoProyecto.setText("Tipo Proyecto");
        mnuTipoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTipoProyectoActionPerformed(evt);
            }
        });
        mnConfiguracion.add(mnuTipoProyecto);

        jMenuItem1.setText("Costo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnConfiguracion.add(jMenuItem1);

        jmenu.add(mnConfiguracion);

        setJMenuBar(jmenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 113, Short.MAX_VALUE)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProyectoActionPerformed
        this.gestorVista.abrirProyecto(getEscritorio());
    }//GEN-LAST:event_mnuProyectoActionPerformed

    private void mnuTipoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTipoProyectoActionPerformed
        this.gestorVista.abrirTipoProyecto(getEscritorio());
    }//GEN-LAST:event_mnuTipoProyectoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar jmenu;
    private javax.swing.JMenu mnConfiguracion;
    private javax.swing.JMenuItem mnuProyecto;
    private javax.swing.JMenuItem mnuTipoProyecto;
    // End of variables declaration//GEN-END:variables

}
