insert into marca(id,codigo,nombre,pais_id) values
(1,1,'Abarth',(select id from pais where nombrepais ilike 'Italia')),
(2,2,'Alfa Romeo',(select id from pais where nombrepais ilike 'Italia')),
(6,6,'Aston Martin',(select id from pais where nombrepais ilike 'Reino unido')),
(7,7,'Audi',(select id from pais where nombrepais ilike 'Alemania')),
(10,10,'Bentley',(select id from pais where nombrepais ilike 'Reino unido')),
(12,12,'Bmw',(select id from pais where nombrepais ilike 'Alemania')),
(13,13,'Cadillac',(select id from pais where nombrepais ilike 'estados unidos')),
(14,14,'Chevrolet',(select id from pais where nombrepais ilike 'estados unidos')),
(15,15,'Chrysler',(select id from pais where nombrepais ilike 'estados unidos')),
(16,16,'Citroen',(select id from pais where nombrepais ilike 'Francia')),
(21,21,'Daihatsu',(select id from pais where nombrepais ilike 'japón')),
(23,23,'Dodge',(select id from pais where nombrepais ilike 'estados unidos')),
(24,24,'Ferrari',(select id from pais where nombrepais ilike 'Italia')),
(25,25,'Fiat',(select id from pais where nombrepais ilike 'Italia')),
(26,26,'Ford',(select id from pais where nombrepais ilike 'estados unidos')),
(29,29,'Honda',(select id from pais where nombrepais ilike 'japón')),
(30,30,'Hummer',(select id from pais where nombrepais ilike 'estados unidos')),
(31,31,'Hyundai',(select id from pais where nombrepais ilike 'corea del sur')),
(32,32,'Infiniti',(select id from pais where nombrepais ilike 'hong kong')),
(34,34,'Isuzu',(select id from pais where nombrepais ilike 'japón')),
(35,35,'Iveco',(select id from pais where nombrepais ilike 'Italia')),
(37,37,'Jaguar',(select id from pais where nombrepais ilike 'Reino unido')),
(38,38,'Jeep',(select id from pais where nombrepais ilike 'estados unidos')),
(39,39,'Kia',(select id from pais where nombrepais ilike 'corea del sur')),
(41,41,'Lamborghini',(select id from pais where nombrepais ilike 'Italia')),
(42,42,'Lancia',(select id from pais where nombrepais ilike 'Italia')),
(43,43,'Land-rover',(select id from pais where nombrepais ilike 'Reino unido')),
(45,45,'Lexus',(select id from pais where nombrepais ilike 'japón')),
(46,46,'Lotus',(select id from pais where nombrepais ilike 'Reino unido')),
(48,48,'Maserati',(select id from pais where nombrepais ilike 'Italia')),
(50,50,'Mazda',(select id from pais where nombrepais ilike 'japón')),
(51,51,'Mercedes-benz',(select id from pais where nombrepais ilike 'Alemania')),
(53,53,'Mini',(select id from pais where nombrepais ilike 'Reino unido')),
(54,54,'Mitsubishi',(select id from pais where nombrepais ilike 'japón')),
(56,56,'Nissan',(select id from pais where nombrepais ilike 'japón')),
(57,57,'Opel',(select id from pais where nombrepais ilike 'Alemania')),
(58,58,'Peugeot',(select id from pais where nombrepais ilike 'Francia')),
(59,59,'Pontiac',(select id from pais where nombrepais ilike 'estados unidos')),
(60,60,'Porsche',(select id from pais where nombrepais ilike 'Alemania')),
(61,61,'Renault',(select id from pais where nombrepais ilike 'Francia')),
(62,62,'Rolls-royce',(select id from pais where nombrepais ilike 'Reino unido')),
(66,66,'Seat',(select id from pais where nombrepais ilike 'españa')),
(68,68,'Smart',(select id from pais where nombrepais ilike 'Alemania')),
(70,70,'Subaru',(select id from pais where nombrepais ilike 'japón')),
(71,71,'Suzuki',(select id from pais where nombrepais ilike 'japón')),
(74,74,'Toyota',(select id from pais where nombrepais ilike 'japón')),
(77,77,'Volkswagen',(select id from pais where nombrepais ilike 'Alemania')),
(78,78,'Volvo',(select id from pais where nombrepais ilike 'suecia'));
